### ISSUE TITLE
Missing json

### ISSUE THREAD

**Issue by jkoplo** [adhocore/tusc.sh#14]
I'm probably doing something wrong, but I tried following the simple startup and I'm getting:
```
realpath: /home/admin/.tus.json: No such file or directory
./tusc.sh: line 84: $TUSFILE: ambiguous redirect
```

I'm on an embedded Linux distro, but I installed `jq` just fine and I'm pretty sure all the other dependencies are in place.

**Comment by adhocore** [comment]
is the /home/admin dir available?

**Comment by adhocore** [comment]
it seems in that specific Linux distro realpath expects existing file

**Comment by adhocore** [comment]
should be fixed in new release
https://github.com/adhocore/tusc.sh/releases/tag/0.8.1 

please feel free to check/verify and reopen issue if issue persists
