### ISSUE TITLE
curl: (6) Could not resolve host: Bearer | "You can pass in anything after -- as extra curl parameter"

### ISSUE THREAD

**Issue by dw5** [adhocore/tusc.sh#18]
![image](https://github.com/adhocore/tusc.sh/assets/29355584/af566c49-2932-424e-b48f-644f2c934cad)

sure... EVERYTHING! sadly even the example doesn't seem to work

![image](https://github.com/adhocore/tusc.sh/assets/29355584/6887623a-e29e-4b14-95f0-d30159df452d)

and yes, all dependencies are there.
![image](https://github.com/adhocore/tusc.sh/assets/29355584/ace49584-f9c4-46ae-8eb7-ca36a6a1ec82)

**Comment by adhocore** [comment]
it was tested feature, the parts after -- are passed as curl args https://github.com/adhocore/tusc.sh/blob/main/tusc.sh#L181

may be it is platform/portability issue or something. where did you run it?

**Comment by adhocore** [comment]
can you try with quotes?

```sh
tusc -H 0:1080 -f ww.mp4 -b /store/ -- "-H 'Authorization: Bearer <token>'"
```
