### ISSUE TITLE
tus version shows as 0.8.1

### ISSUE THREAD

**Issue by happysalada** [adhocore/tusc.sh#20]
when doing tusc --help
When you have a moment if you want to update it to 1.0.0 ?
not a big deal though.
Maybe you can make another github release with the latest pr merged as well.
Thanks a lot for making this!

**Comment by adhocore** [comment]
ah right not a big deal. thanks for raising it. 1.0.0 is basically just same as 0.8.1 https://github.com/adhocore/tusc.sh/releases/tag/v1.0.0 marked for stability. 

previously i used to release with [please](https://github.com/adhocore/please) which would automatically bump version everywhere, but 1.0.0 was done manually in github itself so it might have missed it. 

but again this is not a big deal as feature wise it is same

**Comment by adhocore** [comment]
but also a new release is overdue so releasing it today :D

**Comment by adhocore** [comment]
released [1.0.2](https://github.com/adhocore/tusc.sh/releases/tag/1.0.2) (v1.0.2 does not have v prefix in tag name)
